export ZSH=/home/dave/.oh-my-zsh

ZSH_THEME="dave"

HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000

plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

# copy pwd to xclip
alias cpwd="pwd | xclip"

# Git
alias gs="git status"
alias gb="git branch"
alias gba="git branch -a"

# launch sublime text in terminal
alias subl="/opt/sublime_text/sublime_text"
alias s="/opt/sublime_text/sublime_text"

# open path in gui
alias open="/usr/bin/nautilus"

alias c="chromium-browser --incognito --start-maximized"

# nvidia-smi
alias n="nvidia-smi"

